### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by mrdonthave** [paulzi/filestyler#2]
Hi and thank you for this jQuery Plugin.

How can i get the **names of the files** on server side if i  upload using base64 mode?
I got only the base64 encoded data.

Would you may comfortable with an snippet?

**Comment by paulzi** [comment]
Hi!
In base64 mode filenames is not send to server.
If you need transmit filenames in this mode, you can write [custom template](https://github.com/paulzi/filestyler#templates), with:
```
<input type="hidden" name="{{data.filestyler.$input.attr('name')}}_name" value="{{file.name}}"/>
```
